version: '2'

services:
  web:
    build: .
    depends_on:
      - "db"
    command: bash -c "./wait-for-it.sh db:5432 && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  db:
    image: postgres:10
